CREATE TABLE IF NOT EXISTS Dim_Recalls (
    NHTSA_ID TEXT UNIQUE PRIMARY KEY,   --X
    REPORT_RECEIVED_DATE TEXT NOT NULL, --X
    RECALL_LINK TEXT NOT NULL,          --X
    MANUFACTURER TEXT NOT NULL,         --X
    SUBJECT_ TEXT NOT NULL,
    COMPONENT TEXT NOT NULL,            --X
    MFR_CAMPAIGN_NUMBER TEXT,
    RECALL_TYPE TEXT,                   --X
    POTENTIALLY_AFFECTED INTEGER,       --X
    RECALL_DESCRIPTION TEXT,            --X
    CONSEQUENCE_SUMMARY TEXT,           --X
    CORRECTIVE_ACTION TEXT,
    IS_OPEN INTEGER NOT NULL,
    FUNCTION_ TEXT NOT NULL,            --X
    FAILURE_MODE TEXT,                  --X
    EXTRACTED_DATE DATE -- Datelike string: mm/dd/yyyy
		CHECK(length(EXTRACTED_DATE) == 10)
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS Dim_Grid (
    GRID_ID INTEGER UNIQUE PRIMARY KEY,
    MODEL TEXT NOT NULL,
    BINING TEXT NOT NULL,
    ISSUE TEXT NOT NULL,
    FUNCTION_ TEXT NOT NULL,
    ISSUE_TITLE TEXT NOT NULL,
    DESCRIPTION_ TEXT  NOT NULL,
    AFFECTED_VEHICLES TEXT  NOT NULL,
    DAYS_OPEN_IN_CCRG INTEGER,
    DAYS_OPEN_IN_CSF INTEGER,
    DAYS_OPEN_IN_GOV INTEGER,
    DAYS_OPEN_IN_EPRC INTEGER,
    FCA TEXT NOT NULL,
    OVERALL_STATUS TEXT  NOT NULL,
    GRID_CREATION_DATE TEXT NOT NULL
		CHECK(length(EXTRACTED_DATE) == 10)
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS Dim_Location (
  LOCATION_ID INTEGER UNIQUE PRIMARY KEY,
  COUNTRY TEXT NOT NULL,
  STATE_SUFFIX TEXT NOT NULL,
  FULL_STATE TEXT NOT NULL,
  REGION TEXT NOT NULL
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS Dim_Warraties (
	WARRANTY_ID INTEGER UNIQUE PRIMARY KEY,
	STATUS_ TEXT,				-- Open, closed or monitoring (possiboly relates to FSA)
	CLAIM_KEY REAL,				-- ID for Repairs (LIKE ODINO)
	FAILURE_MODE TEXT,
	CLAIM_TYPE TEXT,			-- Acronims for claim (verify with lucas)
	DTC TEXT,					-- Stands for 'Diagnostic Trouble Code'
	TIS INTEGER,				-- Time in service (number of months)
	ODO INTEGER,				-- amaibe stands for odometer (car miles ?)
	CLAIN_DATA TEXT 			-- Date of claim "MM/DD/YYYY"
		CHECK(length(CLAIN_DATA) == 10), 
	REPAIR_DATE TEXT
		CHECK(length(REPAIR_DATE) == 10), 
	VEHICLE_BUILD_DATE TEXT
		CHECK(length(VEHICLE_BUILD_DATE) == 10), 
	MODEL_YEAR INTEGER,
	VEHICLE_TYPE TEXT,
	PROPUTION_TYPE TEXT,
	CAUSAL_BASE TEXT,			-- Primary (real ?) cause of the problem ?
	MATERIAL_COST REAL,
	TOTAL_COST REAL,
	PACK_SN TEXT,				-- Giant Big Crazy Code
	ECB_BINNING TEXT,
	CREATED_AT TEXT
		CHECK(length(CREATED_AT) == 10), 
	MODIFIED_AT TEXT
		CHECK(length(MODIFIED_AT) == 10), 
	REPLACED_PARTS TEXT,
	TECHNICAL_COMMENTS TEXT,
	CUSTOEMER_COMMENTS TEXT,
	DEALER TEXT,
	WCC TEXT,							-- VFG part specificaiton
	CAUSAL_PREFIX TEXT,
	CAUSAL_SUFFIX TEXT,
	CCC TEXT,							-- other minor VFG part specificaiton
	COND_CODE TEXT,						-- Code of gta 6 sheets
	VFG TEXT,
	NOTES TEXT,
	AWS_MAINTENANCE_DATE TEXT,  		-- Load (Cutoff) date
	ALIAS TEXT,
	CLAIM_STATUS TEXT,
	ECB INTEGER,						-- Boolean field for something
	PACK_BUILD_DATE TEXT
		CHECK(length(PACK_BUILD_DATE) == 10), 
	COUNT_RELATED_COMPONENT INTEGER,
	T50$ INTEGER,						-- no one knows, realy great music
	T50_ INTEGER,
	ECB_COMMENTS TEXT,					-- kill latter
	T50$_STATUS INTEGER,
	T50_STATUS INTEGER,
	CUST_IMPACT TEXT,					-- maybe is important, maintain
	MATCH_EXEMPT INTEGER,
	PRIMARY_DTCS TEXT,
	ECB_EXCEPTION INTEGER,
	ID_DEL INTEGER,
	SYSTEM_EXPORT TEXT,
	CREATED_BY TEXT 
	MODIFIED_BY TEXT,
	KEYWORDS TEXT,						-- Created at processemnt
	
	-- Foreign keys definitions
	LOCATION_ID INTEGER,
	FOREIGN KEY (LOCATION_ID)
		REFERENCES Dim_Location (LOCATION_ID)
			ON UPDATE CASCADE
			ON DELETE SET NULL
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS Dim_Complaints (
	CMPLID INTEGER UNIQUE PRIMARY KEY, -- SEE OTHER COLUMNS FOR PRIMARY KEY
	ODINO INTEGER NOT NULL,
	MFR_NAME TEXT NOT NULL,
	MAKETXT TEXT NOT NULL,
	MODELTXT TEXT NOT NULL,
	YEARTXT TEXT NOT NULL,
	FAILDATE TEXT NOT NULL,
	VIN TEXT NOT NULL,
	LDATE TEXT NOT NULL,
	MILES INTEGER        
	OCCURENCES INTEGER
	CDESCR TEXT NOT NULL, 
	COMPONET TEXT
	FAILURE TEXT
	BINNING TEXT
		CHECK(lenght(BINNING) == (lenght(COMPONET) + lenght(FAILURE) + 3)),
	FAIL_QUARTER TEXT NOT NULL,            
	FULL_VIN UNIQUE TEXT                 
	PROD_DATE DATE                
	VFG TEXT 
	Vehicle_Line_WERS TEXT        
	Vehicle_Line_GSAR TEXT        
	Vehicle_Line_Global TEXT      
	Assembly_Plant TEXT           
	Warranty_Start_Date DATE
	EXTRACTED_DATE TEXT NOT NULL
		CHECK(lenght(EXTRACsTED_DATE) == 10), 
	FAILURE_MODE TEXT NOT NULL,
	Mileage_Class TEXT NOT NULL,

	-- Foreign keys definitions
	LOCATION_ID INTEGER,
	FOREIGN KEY (LOCATION_ID) REFERENCES
		Dim_Location (LOCATION_ID)
			ON UPDATE CASCADE
	      	ON DELETE SET NULL;

	GRID_ID INTEGER,
	FOREIGN KEY (GRID_ID)
		REFERENCES Dim_Grid (GRID_ID)
			ON UPDATE CASCADE
			ON DELETE SET NULL;

	RECALL_ID TEXT, 			--VERIFY RELATIONSHIPS BETWEEN TABLES
	FOREIGN KEY (RECALL_ID)
		REFERENCES Dim_Recalls (RECALL_ID)
			ON UPDATE CASCADE
			ON DELETE SET NULL;

	WARRANTIES_ID INTEGER,		--VERIFY RELATIONSHIPS BETWEEN TABLES
	FOREIGN KEY (WARRANTIES_ID)
		REFERENCES Dim_Warraties (WARRANTIES_ID)
			ON UPDATE CASCADE
			ON DELETE SET NULL;
) WITHOUT ROWID;
