"""
This module defines the main schemas for the extraction stage with
raw_complaint dataset
"""

from pandas import Timestamp
from pandera import DataFrameSchema, Column, Check, Int, String, Bool

schema = DataFrameSchema(
    columns={
        "CMPLID": Column(
            dtype=Int,
            unique=True,
            required=True,
            coerce=True,
            description="ID of the complaint on NHTSA",
            title="COMPLAINT ID",
        ),
        "ODINO": Column(
            dtype=Int,
            unique=True,
            required=True,
            coerce=True,
            description="ODI number of the vehicle",
            title='VEHICLE "ODI" NUMBER',
        ),
        "MFR_NAME": Column(
            dtype=String,
            nullable=True,
            required=True,
            description="Name of the vehicle Manufacturer",
            title="MANUFACTURER NAME",
        ),
        "MAKETXT": Column(
            dtype=String,
            nullable=True,
            required=True,
            description="Name of the vehicle Make",
            title="MAKE NAME",
        ),
        "MODELTXT": Column(
            dtype=String,
            nullable=True,
            required=True,
            description="Name of the vehicle Model",
            title="MODEL NAME",
        ),
        "YEARTXT": Column(
            dtype=Int,
            checks=[
                Check.between(min_value=1910, max_value=2030),
            ],
            nullable=True,
            required=True,
            coerce=True,
            description="Year of the vehicle fabrication",
            title="FABRICAITON YEAR",
        ),
        "CRASH": Column(
            dtype=Bool, required=True, description="Complaint related a Crash case"
        ),
        "FAILDATE": Column(
            dtype=Int,
            required=True,
            coerce=True,
            description="Complaint failure dated in YYYYMMDD format",
            title="DATE OF FAILURE",
        ),
        "FIRE": Column(
            dtype=Bool, required=True, description="Complaint related a Fire start case"
        ),
        "INJURED": Column(
            dtype=Int,
            checks=[Check.between(min_value=0, max_value=99)],
            coerce=True,
            required=True,
            description="Number of people injuried involved in the incident",
        ),
        "DEATHS": Column(
            dtype=Int,
            checks=[Check.between(min_value=0, max_value=99)],
            coerce=True,
            required=True,
            description="Number of deaths involved in the incident",
        ),
        "COMPDESC": Column(
            dtype=String,
            nullable=True,
            required=True,
            description="Description of the problematic component (not reliable)",
            title="COMPONENT DESCRIPTION",
        ),
        "CITY": Column(
            dtype=String,
            nullable=True,
            required=True,
            description=None,
        ),
        "STATE": Column(
            dtype="object",
            required=True,
            description=None,
        ),
        "VIN": Column(
            dtype=String,
            nullable=True,
            required=True,
            description="Vehicle Identification Number",
        ),
        "DATEA": Column(
            dtype="datetime64[ns]",
            checks=[
                Check.between(
                    min_value=Timestamp(19100101, tz="UTC"),
                    max_value=Timestamp(20301231, tz="UTC"),
                )
            ],
            coerce=True,
            required=True,
            description="Date when the complaint was added to NHTSA database in YYYYMMDD format",
            title="DATE ADDED",
        ),
        "LDATE": Column(
            dtype="datetime64[ns]",
            checks=[
                Check.between(
                    min_value=Timestamp(19100101, tz="UTC"),
                    max_value=Timestamp(20301231, tz="UTC"),
                )
            ],
            coerce=True,
            required=True,
            description="Date when the complaint was received by NHTSA in YYYYMMDD format",
            title="DATE RECEIVED",
        ),
        "MILES": Column(
            dtype=Int,
            checks=[Check.greater_than_or_equal_to(min_value=0.0)],
            coerce=True,
            nullable=True,
            required=True,
            description="Total miles of the vehicle",
        ),
        "OCCURENCES": Column(
            dtype=Int,
            checks=[
                Check.between(min_value=0.0, max_value=99.0),
            ],
            coerce=True,
            nullable=True,
            required=True,
            description="number of times that the problem occured",
        ),
        "CDESCR": Column(
            dtype=String,
            nullable=True,
            required=True,
            description="Complaint description",
            title="COMPLAINT TEXT",
        ),
        "CMPL_TYPE": Column(
            dtype=String,
            required=True,
            description="Complaint type",
            title="COMPLAINT TYPE",
        ),
        "POLICE_RPT_YN": Column(
            dtype=Bool,
            required=True,
            description="Police report on the incident",
            title="POLICE REPORT",
        ),
        "PURCH_DT": Column(
            dtype="datetime64[ns]",
            checks=[Check.greater_than_or_equal_to(min_value=19800101)],
            nullable=True,
            required=True,
            description="Date when the vehicle was purchased in YYYYMMDD format",
            title="PURCHASE DATE",
        ),
        "ORIG_OWER_YN": Column(
            dtype=Bool,
            nullable=True,
            required=True,
            description="Original owner of the vehicle",
            title="ORIGINAL OWNER",
        ),
        "ANTI_BRAKES_YN": Column(
            dtype=Bool,
            nullable=True,
            required=True,
            description="Vehicle has anti brakes",
            title="ANTI BRAKES",
        ),
        "CRUISE_CONT_YN": Column(
            dtype=Bool,
            nullable=True,
            required=True,
            description="Vehicle has cruise control",
            title="CRUISE CONTROL",
        ),
        "NUM_CYLS": Column(
            dtype=Int,
            checks=[
                Check.between(min_value=0.0, max_value=16.0),
            ],
            coerce=True,
            nullable=True,
            required=True,
            description="Number of cylinders, 0 to 16",
            title="NUMBER OF CYLINDERS",
        ),
        "DRIVE_TRAIN": Column(
            dtype=String,
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "FUEL_SYS": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "FUEL_TYPE": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "TRASN_TYPE": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "VEH_SPEED": Column(
            dtype="float64",
            checks=[
                Check.greater_than_or_equal_to(min_value=0.0),
                Check.less_than_or_equal_to(max_value=999.0),
            ],
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "DOT": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "TIRE_SIZE": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "LOC_OF_TIRE": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "TIRE_FAIL_TYPE": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "ORIG_EQUIP_YN": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "MANUF_DT": Column(
            dtype="float64",
            checks=[
                Check.greater_than_or_equal_to(min_value=20020501.0),
                Check.less_than_or_equal_to(max_value=20231021.0),
            ],
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "SEAT_TYPE": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "RESTRAINT_TYPE": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "DEALER_NAME": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "DEALER_TEL": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "DEALER_CITY": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "DEALER_STATE": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "DEALER_ZIP": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "PROD_TYPE": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "REPAIRED_YN": Column(
            dtype="object",
            nullable=True,
            required=True,
            description=None,
            title=None,
        ),
        "MEDICAL_ATTN": Column(
            dtype="object",
            required=True,
            description=None,
            title=None,
        ),
        "VEHICLES_TOWED_YN": Column(
            dtype=Bool,
            nullable=True,
            required=True,
            description="Vehicle has been towed",
        ),
    },
    dtype=None,
    coerce=True,
    strict=False,
    name=None,
    ordered=False,
    unique=None,
    report_duplicates="all",
    unique_column_names=False,
    title=None,
    description=None,
)
